CREATE TABLE User (
 UserID VARCHAR(30) NOT NULL,
 Email CHAR(10) NOT NULL,
 PasswordHashMD5 VARCHAR(30),
 UserName VARCHAR(30) NOT NULL,
 ResetPasswordID VARCHAR(30)
);

ALTER TABLE User ADD CONSTRAINT PK_User PRIMARY KEY (UserID);


CREATE TABLE LoginSession (
 UserID VARCHAR(30) NOT NULL,
 SessionID VARCHAR(30) NOT NULL
);

ALTER TABLE LoginSession ADD CONSTRAINT PK_LoginSession PRIMARY KEY (UserID);


CREATE TABLE PPMKProject (
 ProjectID VARCHAR(30) NOT NULL,
 OwnerUserID VARCHAR(30) NOT NULL,
 ProjectName VARCHAR(50) NOT NULL,
 IsSharedView VARCHAR(30) NOT NULL
);

ALTER TABLE PPMKProject ADD CONSTRAINT PK_PPMKProject PRIMARY KEY (ProjectID);


CREATE TABLE PPMKProjectData (
 ProjectDataID VARCHAR(30) NOT NULL,
 ProjectID VARCHAR(30) NOT NULL,
 SavedTime VARCHAR(30) NOT NULL,
 ProjectData VARCHAR(1) NOT NULL,
 Author CHAR(10) NOT NULL
);

ALTER TABLE PPMKProjectData ADD CONSTRAINT PK_PPMKProjectData PRIMARY KEY (ProjectDataID);


CREATE TABLE ProjectShare (
 ProjectID VARCHAR(30) NOT NULL,
 UserID VARCHAR(10) NOT NULL,
 Writable VARCHAR(10)
);

ALTER TABLE ProjectShare ADD CONSTRAINT PK_ProjectShare PRIMARY KEY (ProjectID,UserID);


ALTER TABLE LoginSession ADD CONSTRAINT FK_LoginSession_0 FOREIGN KEY (UserID) REFERENCES User (UserID);


ALTER TABLE PPMKProject ADD CONSTRAINT FK_PPMKProject_0 FOREIGN KEY (OwnerUserID) REFERENCES User (UserID);


ALTER TABLE PPMKProjectData ADD CONSTRAINT FK_PPMKProjectData_0 FOREIGN KEY (ProjectID) REFERENCES PPMKProject (ProjectID);


ALTER TABLE ProjectShare ADD CONSTRAINT FK_ProjectShare_0 FOREIGN KEY (ProjectID) REFERENCES PPMKProject (ProjectID);


