CREATE TABLE IF NOT EXISTS User (
    UserID VARCHAR(30) NOT NULL PRIMARY KEY,
    Email VARCHAR(30) NOT NULL,
    PasswordHashMD5 VARCHAR(30) NOT NULL,
    UserName VARCHAR(30) NOT NULL,
    ResetPasswordID VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS LoginSession (
    SessionID VARCHAR(30) NOT NULL PRIMARY KEY,
    UserID VARCHAR(30) NOT NULL,
    FOREIGN KEY (UserID) REFERENCES User(UserID)
);

CREATE TABLE IF NOT EXISTS PPMKProject (
    ProjectID VARCHAR(30) NOT NULL PRIMARY KEY,
    OwnerUserID VARCHAR(30) NOT NULL,
    ProjectName VARCHAR(50) NOT NULL,
    IsSharedView VARCHAR(30) NOT NULL,
    FOREIGN KEY (OwnerUserID) REFERENCES User(UserID)
);

CREATE TABLE IF NOT EXISTS PPMKProjectData (
    ProjectDataID VARCHAR(30) NOT NULL PRIMARY KEY,
    ProjectID VARCHAR(30) NOT NULL,
    SavedTime VARCHAR(30) NOT NULL,
    ProjectData VARCHAR(1) NOT NULL,
    Author VARCHAR(30) NOT NULL,
    Memo VARCHAR(30) NOT NULL,
    FOREIGN KEY (ProjectID) REFERENCES PPMKProject(ProjectID)
);

CREATE TABLE IF NOT EXISTS ProjectShare (
    ProjectID VARCHAR(30) NOT NULL,
    UserID VARCHAR(10) NOT NULL,
    Writable VARCHAR(10) NOT NULL,
    FOREIGN KEY (ProjectID) REFERENCES PPMKProject(ProjectID)
	PRIMARY KEY(ProjectID, UserID)
);
