CREATE TABLE User (
 UserID CHAR(30) NOT NULL,
 UserName VARCHAR(30) NOT NULL,
 PasswordHashMD5 CHAR(32)
);

ALTER TABLE User ADD CONSTRAINT PK_User PRIMARY KEY (UserID);


CREATE TABLE LoginSession (
 UserID CHAR(30) NOT NULL,
 SessionID VARCHAR(30) NOT NULL
);

ALTER TABLE LoginSession ADD CONSTRAINT PK_LoginSession PRIMARY KEY (UserID);


CREATE TABLE PPMKProjectData (
 ProjectID CHAR(30) NOT NULL,
 UserID CHAR(30) NOT NULL,
 ProjectName VARCHAR(10) NOT NULL,
 ProjectData VARCHAR(10) NOT NULL,
 IsShared BIT(2) NOT NULL
);

ALTER TABLE PPMKProjectData ADD CONSTRAINT PK_PPMKProjectData PRIMARY KEY (ProjectID);


ALTER TABLE LoginSession ADD CONSTRAINT FK_LoginSession_0 FOREIGN KEY (UserID) REFERENCES User (UserID);


ALTER TABLE PPMKProjectData ADD CONSTRAINT FK_PPMKProjectData_0 FOREIGN KEY (UserID) REFERENCES User (UserID);


